pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'webapp-acr-conn'   
    repository: 'fastapi-app'             # Image name in your ACR
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'              # Path to your Dockerfile
    tags: 'latest'
