trigger:
  branches:
    include:
      - main

pool:
  name: Default

variables:
  imageName: 'fastapi-app'

steps:
- task: Docker@2
  displayName: 'Build and Push to ACR'
  inputs:
    containerRegistry: 'webapp-acr-conn'
    repository: 'fastapi-app'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: |
      latest
