trigger:
  branches:
    include:
      - main  # or whatever branch you want to trigger this from

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'webappproject'
    repository: 'fastapi-app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
