trigger:
  branches:
    include:
      - main  # Trigger pipeline on commits to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'azure-fastapi-app'

steps:
- task: Docker@2
  inputs:
    containerRegistry: '<Your-ACR-Service-Connection>'  # Azure Container Registry connection in DevOps
    repository: webapp.azurecr.io/$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
    buildContext: .
